server:
  port: 8081

spring:
  application:
    name: exchange-aggregation-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
      max-request-size: 2MB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/exchange-aggregation-service'
    username: 'admin'
    password: 'exchangeaggregationservice'
    hikari:
      auto-commit: false
  data:
    redis:
      repositories:
        enabled: true
      port: 6379
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092,kafka:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.tradesoft.exchangeaggregationservice.periphery.events"
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: exchange-metadata
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual_immediate
      concurrency: 1
      idle-between-polls: 3000
      poll-timeout: 700000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

Kafka:
  topics:
    exchange-metadata: exchange-metadata

logging:
  level:
    root: trace
    org:
      springframework:
        web: trace
        kafka: trace
      apache:
        kafka: trace
        tomcat: trace
    web: trace
    com:
      tradesoft: trace

app:
  title: 'Exchange Aggregation Service'
  description: 'A simple microservice to aggregate exchange data'
  version: '1.0'
  tosUrl: 'https://www.tradesoft.pro/confidential/'
  license: 'Apache Commons License'
  licenseUrl: 'https://www.tradesoft.pro/confidential/'
  authorName: 'Anietie Asuquo'
  authorUrl: 'https://anietieasuquo.com'
  authorEmail: 'hello@anietieasuquo.com'

blockchaindotcom:
  service:
    url: 'https://api.blockchain.com/v3/exchange'
pagination:
  config:
    metadata-default-page-size: 100

cache:
  exchangeMetadataCacheName: exchange-metadata-cache
  exchangeMetadataCacheDurationInMinutes: 43200
  exchangeMetadataUploadCacheName: exchange-metadata-upload-cache
  exchangeMetadataUploadCacheDurationInMinutes: 43200

springdoc:
  swagger-ui:
    use-root-path: true
  show-actuator: true
